INSERT INTO USERS(ID, NAME, OWNER) VALUES (100, 'Carlos', 'admin');
INSERT INTO USERS(ID, NAME, OWNER) VALUES (101, 'Luis', 'admin');
INSERT INTO USERS(ID, NAME, OWNER) VALUES (102, 'Andrés', 'admin');